spring:
  datasource:
    url: jdbc:postgresql://rc1b-0ckq9oilrgugcaer.mdb.yandexcloud.net:6432/javapro
    username: javapro
    password: ELncWdLB
  liquibase: # liquibase ??? ??????? sql ???????? ?? ??
    enabled: false
    change-log: classpath:db/changelog-master.yml
    liquibase-schema: liquibase
  application: # ???????? ??????????
    name: card
  cloud:
    loadbalancer:
      ribbon:
        enabled: false # ????????? spring-cloud -> ????????????? ?? eureka

#jwt: # ??? JwtUtils (?????? ???? ? ?????? ??????? ????????? ? ???????????? ??)
#  secret: secret # ???? ??? ????
#  token:
#    validity: 1000000000000 # ???????????? ???????? ??????

server:
  port: 8082 # ?????????????? ???? (?? ????????? 8080) - ?? ??????? 9002